services:
  firebase:
    build: ./docker/dev/firebase
    restart: always
    ports:
      - 9099:9099 # Auth
      - 4000:4000 # Emulator Suite UI
    env_file:
      - ./docker/dev/.env
    working_dir: /opt/workspace
    command: firebase emulators:start --only=auth --project=emulator --import ./firebase-export --export-on-exit

  minio:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    restart: always
    ports:
      - 9000:9000 # Storage
      - 9001:9001 # Console
    env_file:
      - ./docker/dev/.env
    volumes:
      - ./docker/dev/minio/data:/data
    entrypoint: []
    command: minio server /data --console-address :9001
    healthcheck:
      test: curl -I http://localhost:9000/minio/health/live
      interval: 5s

  mc:
    image: minio/mc:RELEASE.2023-08-18T21-57-55Z
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ./docker/dev/.env
      - ./server/.env
    entrypoint: []
    command: |
      sh -c "
        set -euxo pipefail
        mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc mb myminio/$$S3_BUCKET --region=$$S3_REGION || true
        mc anonymous set download myminio/$$S3_BUCKET
      "

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./docker/dev/.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
